
    // // Test for uniqueness
    // if (uniqueImageIds.has(imageId)) {
    //   console.log(`❌ Duplicate found! Image ID "${imageId}" was already generated by a previous seed.`);
    // } else {
    //   uniqueImageIds.add(imageId);
    //   console.log(`✅ Unique Image Tracking: Added ID "${imageId}" (Seed: ${seed})`);
    // }

//   } catch (error) {
//     console.error("Network or CORS error fetching image headers:", error);
//   }
