
    // // Test for uniqueness
    // if (uniqueImageIds.has(imageId)) {
    //   console.log(`❌ Duplicate found! Image ID "${imageId}" was already generated by a previous seed.`);
    // } else {
    //   uniqueImageIds.add(imageId);
    //   console.log(`✅ Unique Image Tracking: Added ID "${imageId}" (Seed: ${seed})`);
    // }

//   } catch (error) {
//     console.error("Network or CORS error fetching image headers:", error);
//   }

// &#013; FOR LINE-BREAK IN TOOLTIPS




//--------------------------------------  TEST DATA  -----------------------------------

    const imageLinks = Array.from([

        {
            "address":    "random@company.com",
            "images": {
                "image-1": {

                    "UID":          "152",
                    "url":          "https://picsum.photos/seed/vx7zk2p/500/280.webp"
                }
                ,
                "image-2": {

                    "UID":          "921",
                    "url":          "https://picsum.photos/seed/s334u0i/500/280.webp"
                }
            }
        }
        ,
        {
            "address":    "info@institution.gov",
            "images": {
                "image-1": {

                    "UID":          "516",
                    "url":          "https://picsum.photos/seed/p4ecvz1/500/280.webp"
                }
                ,
                "image-2": {

                    "UID":          "360",
                    "url":          "https://picsum.photos/seed/rmh1f3j/500/280.webp"
                }
                ,
                "image-3": {

                    "UID":          "1008",
                    "url":          "https://picsum.photos/seed/797d8mz/500/280.webp"
                }
                ,
            }

        }
        ,
        {
            "address":    "neil@home.com",
            "images": {
                "image-1": {

                    "UID":          "914",
                    "url":          "https://picsum.photos/seed/naicmff/500/280.webp"
                }
                ,
                "image-2": {

                    "UID":          "93",
                    "url":          "https://picsum.photos/seed/q8evrm7/500/280.webp"
                }
                ,
                "image-3": {

                    "UID":          "368",
                    "url":          "https://picsum.photos/seed/8qa00ap/500/280.webp"
                }
                ,
            }

        }
    ]);

    // console.log(imageLinks);

//--------------------------------------------------------------------------------------


